### ISSUE TITLE
Hi my friend, what is going on ? [Errno 2] No such file or directory: '../datasets/WN31/EN_DE_15K_V1/pre/path_neigh_dict'

### ISSUE THREAD

**Issue by daima2017** [cwswork/RPR_RHGT#1]
How to get the file, "path_neigh_dict"?
[Errno 2] No such file or directory: '../datasets/WN31/EN_DE_15K_V1/pre/path_neigh_dict'

**Comment by cwswork** [comment]
https://www.jianguoyun.com/p/DWzhBksQ2t_lCBjon78EIAA#dir=%2FWN31%2FEN_DE_15K_V1%2Fpre::mode=0
![image](https://user-images.githubusercontent.com/59187027/169454599-5962108d-4f24-493d-87f9-c8e3832a22a3.png)
