### ISSUE TITLE
Hi, my friend. Can you tell me how the data under the pre file is generated?

### ISSUE THREAD

**Issue by daima2017** [cwswork/RPR_RHGT#3]
Can you tell me how the data under the pre file is generated?
I would like to experiment with my own data.

Would you like to share your scripts and detailed steps for making pre-processed data?

thanks very much!

![image](https://user-images.githubusercontent.com/44838048/177001564-deb26876-ef33-4d67-9527-2e7c40b5f121.png)

**Comment by cwswork** [comment]
hi, which university are you from and what do you do?







Weishan Cai
 
***@***.***

***@***.***
 
School of Computer Science
 
South China Normal University
 
Guangzhou 510631 P.R. China



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwswork/RPR_RHGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月2日(星期六) 晚上8:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cwswork/RPR_RHGT] Hi, my friend. Can you tell me how the data under the pre file is generated? (Issue #3)





 
Can you tell me how the data under the pre file is generated?
 I would like to experiment with my own data.
 
Would you like to share your scripts and detailed steps for making pre-processed data?
 
thanks very much!

**Comment by daima2017** [comment]
hi, my friend, i come from Zhe Jiang University. I am a Phd-student,  hahaha.
Working hard...
